title:              Joseph's blog
email:              josephw@tuta.io
description:        腦袋的洞在這裡補
author:             Joseph
baseurl:            "/"
url:                "https://josephjsf2.github.io"

# Social Profiles
twitter_username:   
github_username:    josephjsf2
facebook_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-135933368-1 # out your google-analytics code


# Build settings
markdown:           kramdown
highlighter:        rouge
paginate:           20
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-seo-tag

